name: FakeEconomy
version: ${project.version}
main: de.themoep.fakeeconomy.FakeEconomy
api-version: 1.13
depend: [Vault]
authors: [Phoenix616]
description: Not a real economy...
commands:
  fakeeconomy:
    aliases:
      - fe
      - money
      - economy
      - eco
    usage: /<command> balance <player>|setbalance <player> <amount>